version: '3'
services:
  monolito:
      build: ./monolito

  orderservice:
    build: ./orderservice
    environment:
      - monolito.server=http://monolito:8080/

  apigateway:
    build: ./api-gateway
    depends_on: 
      - monolito
      - orderservice
    ports:
      - "8080:8080"
    environment:
      - order.destinations.orderServiceUrl=http://orderservice:8080/
      - webhook.destinations.webhookServiceUrl=http://monolito:8080/
      - customer.destinations.customerServiceUrl=http://monolito:8080/
      - product.destinations.productServiceUrl=http://monolito:8080/