version: '3'
services:
  notificationservice:
    build: ./notificationservice

  monolith:
    build: ./monolito
    depends_on: 
      - notificationservice
    environment:
      - feature.toggle.notification.proxy=true
      - notification.server=http://notificationservice:8080/

  orderservice:
    build: ./orderservice
    environment:
      - monolith.server=http://monolith:8080/

  apigateway:
    build: ./api-gateway
    depends_on: 
      - monolith
      - orderservice
    ports:
      - "8080:8080"
    environment:
      - order.destinations.orderServiceUrl=http://orderservice:8080/
      - webhook.destinations.webhookServiceUrl=http://monolith:8080/
      - customer.destinations.customerServiceUrl=http://monolith:8080/
      - product.destinations.productServiceUrl=http://monolith:8080/