version: '3'
services:
  monolito:
      build: ./monolito

  orderservice:
    build: ./orderservice

  apigateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
          - order.destinations.orderServiceUrl=http://orderservice:8080/
          - customer.destinations.customerServiceUrl=http://monolito:8080/
          - product.destinations.productServiceUrl=http://monolito:8080/
